### ISSUE TITLE
Game crashes on teleport

### ISSUE THREAD

**Issue by sharmonic** [Tropicraft/Tropicraft#207]
The game starts up fine, and I can start a new world, but as soon as it becomes sunset and I drink a pina colada in a chair, the game crashes. I am using Forge version 1.10.2 and the only mod I am using is Tropicraft. 
Here is the report:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/9/17 11:38 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Lnet/minecraft/world/World;)Lnet/minecraft/entity/EntityLiving;
	at net.tropicraft.core.common.spawning.TropiWorldEntitySpawner.performWorldGenSpawning(TropiWorldEntitySpawner.java:295)
	at net.tropicraft.core.common.dimension.ChunkProviderTropicraft.func_185931_b(ChunkProviderTropicraft.java:99)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:842)
	at net.tropicraft.core.common.dimension.TeleporterTropics.func_180620_b(TeleporterTropics.java:108)
	at net.tropicraft.core.common.dimension.TeleporterTropics.func_180266_a(TeleporterTropics.java:64)
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:696)
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:606)
	at net.tropicraft.core.common.dimension.TropicraftWorldUtils.teleportPlayer(TropicraftWorldUtils.java:37)
	at net.tropicraft.core.common.event.MiscEvents.tickServer(MiscEvents.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_32_MiscEvents_tickServer_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 531915592 bytes (507 MB) / 1006632960 bytes (960 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 50
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAAAAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAAAAAAA	tropicraft{v7.0} [Tropicraft] (tropicraft-7.0.0.110.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['arvenrayner'/1851, l='tropicraft', x=53.00, y=64.00, z=172.00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by tterrag1098** [comment]
Your forge is quite old, can you try the latest version ([2511](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html))?

**Comment by sharmonic** [comment]
looks like that worked! it doesn't crash when teleporting now.

**Comment by okushama** [comment]
great news, enjoy the beta! :)
