### ISSUE TITLE
Server crashes after entering tropical dimension

### ISSUE THREAD

**Issue by MatthewSpofford** [Tropicraft/Tropicraft#220]
When entering the tropical dimension, the server I am running tropiccraft off of crashes once you enter the tropics dimension.  This is the crash report I received:

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 11/24/17 5:07 PM
Description: Watching Server

java.lang.Error
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
	at java.io.PrintStream.write(PrintStream.java:449)
	at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82)
	at java.io.PrintStream.write(PrintStream.java:449)
	at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at jline.console.ConsoleReader.flush(ConsoleReader.java:1032)
	at net.minecraftforge.server.console.TerminalConsoleAppender.append(TerminalConsoleAppender.java:170)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1011)
	at net.minecraftforge.fml.common.TracingPrintStream.println(TracingPrintStream.java:43)
	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
	at java.lang.Throwable.printStackTrace(Throwable.java:658)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:144)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
	at java.io.PrintStream.write(PrintStream.java:449)
	at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82)
	at java.io.PrintStream.write(PrintStream.java:449)
	at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at jline.console.ConsoleReader.flush(ConsoleReader.java:1032)
	at net.minecraftforge.server.console.TerminalConsoleAppender.append(TerminalConsoleAppender.java:170)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1011)
	at net.minecraftforge.fml.common.TracingPrintStream.println(TracingPrintStream.java:43)
	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
	at java.lang.Throwable.printStackTrace(Throwable.java:658)
	at java.lang.Throwable.printStackTrace(Throwable.java:643)
	at java.lang.Throwable.printStackTrace(Throwable.java:634)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:144)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)

-- Thread Dump --
Details:
	Threads: "File IO Thread" Id=60 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:51)
	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
	at java.lang.Thread.run(Thread.java:745)


"Chunk I/O Executor Thread-1" Id=59 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@fa312e2
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@fa312e2
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


"Netty Server IO #1" Id=36 RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@164ed66
	-  locked java.util.Collections$UnmodifiableSet@55b7992
	-  locked sun.nio.ch.WindowsSelectorImpl@4059e75d
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	...


"Server Watchdog" Id=52 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:46)
	at java.lang.Thread.run(Thread.java:745)


"Netty Server IO #0" Id=35 RUNNABLE (in native)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@577ac9b6
	-  locked java.util.Collections$UnmodifiableSet@71d301e2
	-  locked sun.nio.ch.WindowsSelectorImpl@2f1a71a3
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	...


"Timer-0" Id=34 TIMED_WAITING on java.util.TaskQueue@20761812
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@20761812
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)


"Server console handler" Id=28 RUNNABLE (in native)
	at org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method)
	at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761)
	at org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794)
	at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97)
	at jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214)
	at jline.WindowsTerminal.access$000(WindowsTerminal.java:54)
	at jline.WindowsTerminal$1.read(WindowsTerminal.java:156)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	-  locked jline.internal.NonBlockingInputStream@214052d3
	...


"DestroyJavaVM" Id=29 RUNNABLE


"Server thread" Id=26 RUNNABLE
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
	-  locked java.io.BufferedOutputStream@48759b08
	at java.io.PrintStream.write(PrintStream.java:449)
	-  locked java.io.PrintStream@341e7ccc
	at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82)
	at java.io.PrintStream.write(PrintStream.java:449)
	-  locked java.io.PrintStream@243844d5
	at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82)
	...


"TimerQueue" Id=24 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4243246f
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@4243246f
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.DelayQueue.take(DelayQueue.java:223)
	at javax.swing.TimerQueue.run(TimerQueue.java:171)
	at java.lang.Thread.run(Thread.java:745)

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@243bd2d1


"Thread-6" Id=23 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2f019778
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2f019778
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77)
	at net.minecraft.server.gui.MinecraftServerGui$4.run(MinecraftServerGui.java:154)
	at java.lang.Thread.run(Thread.java:745)


"AWT-EventQueue-0" Id=22 RUNNABLE
	at java.lang.Object.notify(Native Method)
	at javax.swing.text.AbstractDocument.readUnlock(AbstractDocument.java:1423)
	-  locked javax.swing.text.PlainDocument@6d94f7db
	at javax.swing.plaf.basic.BasicTextUI.paint(BasicTextUI.java:884)
	at javax.swing.plaf.basic.BasicTextUI.update(BasicTextUI.java:860)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	...


"AWT-Windows" Id=20 RUNNABLE (in native)
	at sun.awt.windows.WToolkit.eventLoop(Native Method)
	at sun.awt.windows.WToolkit.run(WToolkit.java:306)
	at java.lang.Thread.run(Thread.java:745)


"AWT-Shutdown" Id=19 WAITING on java.lang.Object@17c30de2
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@17c30de2
	at java.lang.Object.wait(Object.java:502)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	at java.lang.Thread.run(Thread.java:745)


"Java2D Disposer" Id=18 WAITING on java.lang.ref.ReferenceQueue$Lock@4cf82329
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@4cf82329
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:745)


"Server Infinisleeper" Id=17 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:78)


"Snooper Timer" Id=16 TIMED_WAITING on java.util.TaskQueue@6fe1d799
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@6fe1d799
	at java.util.TimerThread.mainLoop(Timer.java:552)
	at java.util.TimerThread.run(Timer.java:505)


"NonBlockingInputStreamThread" Id=14 WAITING on jline.internal.NonBlockingInputStream@214052d3 owned by "Server console handler" Id=28
	at java.lang.Object.wait(Native Method)
	-  waiting on jline.internal.NonBlockingInputStream@214052d3
	at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
	at java.lang.Thread.run(Thread.java:745)


"Attach Listener" Id=5 RUNNABLE


"Signal Dispatcher" Id=4 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@2501df91
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@2501df91
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@2a227ace
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@2a227ace
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)



Stacktrace:
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:63)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 505195960 bytes (481 MB) / 731381760 bytes (697 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xmx1024M -Xmx1024M
	IntCache: cache: 0, tcache: 29, allocated: 1, tallocated: 50
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511-universal.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	tropicraft{7.0.2.141} [Tropicraft] (tropicraft-7.0.2.141.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['tc3monkey'/318, l='MODPACK SERVER', x=-96.51, y=64.00, z=365.16]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by tterrag1098** [comment]
Server watchdog crashes are basically useless. Increase the max-tick-time option in your server.properties.
