### ISSUE TITLE
flowerpots crashes the game

### ISSUE THREAD

**Issue by Bvioto** [Tropicraft/Tropicraft#241]
Flowerpots crashes the game :/ 

The message after the shutting down came like this:

"The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error"
I don't know anything about java though.

I reseted the game and the pot was there. But the instant I look at it with the cross point the game crashes again.

**Comment by tterrag1098** [comment]
Could you post the whole log?

**Comment by Bvioto** [comment]
Is this the log?


```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  CreativePatchingLoader (CreativeCore+v1.9.14+mc1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  ItemPatchingLoader (ItemPhysic+Full+1.4.10+mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/19/18 12:07 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.tropicraft.core.common.block.BlockTropicraftFlowerPot.func_185473_a(BlockTropicraftFlowerPot.java:134)
	at net.minecraft.block.Block.getPickBlock(Block.java:1585)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:166)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:88)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:59)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:75)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_552_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.tropicraft.core.common.block.BlockTropicraftFlowerPot.func_185473_a(BlockTropicraftFlowerPot.java:134)
	at net.minecraft.block.Block.getPickBlock(Block.java:1585)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:166)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:88)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:59)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:75)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_552_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['bvioto'/448, l='MpServer', x=326.59, y=85.00, z=134.38]]
	Chunk stats: MultiplayerChunkCache: 602, 602
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (232,64,100), Chunk: (at 8,4,4 in 14,6; contains blocks 224,0,96 to 239,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 141228 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 140 total; [EntityItem['item.item.egg'/773, l='MpServer', x=289.45, y=66.00, z=158.40], EntityItem['item.item.egg'/775, l='MpServer', x=273.20, y=67.00, z=148.29], EntityReverseCreeper['Creeper Reversa'/268, l='MpServer', x=324.57, y=28.00, z=89.80], EntityChicken['Gallina'/269, l='MpServer', x=334.54, y=76.00, z=88.63], EntityItem['item.item.egg'/270, l='MpServer', x=334.75, y=76.00, z=88.43], EntityFishCod['Cod'/271, l='MpServer', x=341.52, y=58.22, z=120.53], EntityWindCreeper['Creeper de Viento'/272, l='MpServer', x=324.32, y=68.17, z=137.50], EntitySpringCreeper['Spring Creeper'/273, l='MpServer', x=329.08, y=69.00, z=139.37], EntityItem['item.tile.plants2.fabaceae'/274, l='MpServer', x=325.13, y=86.50, z=130.31], EntitySpringCreeper['Spring Creeper'/787, l='MpServer', x=364.50, y=38.00, z=94.50], EntityItem['item.tile.sapling.oak'/285, l='MpServer', x=347.13, y=83.00, z=79.13], EntityLightCreeper['Creeper de Luz'/286, l='MpServer', x=349.50, y=41.00, z=85.50], EntityBallisticCreeper['Ballistic Creeper'/287, l='MpServer', x=347.50, y=41.00, z=83.50], EntityCreeper['Creeper'/288, l='MpServer', x=350.50, y=61.00, z=94.50], MoCEntitySnake['Snake'/289, l='MpServer', x=338.36, y=78.00, z=78.95], EntityItem['item.tile.sapling.oak'/291, l='MpServer', x=349.77, y=82.00, z=97.49], EntityIceCreeper['Creeper de Hielo'/292, l='MpServer', x=346.50, y=20.00, z=127.50], EntityFishSalmon['Salmon'/293, l='MpServer', x=349.32, y=62.18, z=125.24], EntityFishCod['Cod'/294, l='MpServer', x=347.50, y=60.70, z=113.59], EntityFishSalmon['Salmon'/295, l='MpServer', x=342.65, y=58.89, z=125.09], EntityFishSalmon['Salmon'/296, l='MpServer', x=348.40, y=58.11, z=132.45], EntityFishCod['Cod'/297, l='MpServer', x=347.38, y=59.89, z=132.84], EntityFishCod['Cod'/299, l='MpServer', x=345.61, y=58.93, z=134.80], EntityFishCod['Cod'/300, l='MpServer', x=345.53, y=57.84, z=129.86], EntityFishCod['Cod'/301, l='MpServer', x=343.93, y=57.88, z=127.61], EntityFishCod['Cod'/302, l='MpServer', x=348.41, y=61.13, z=145.76], EntityFishCod['Cod'/303, l='MpServer', x=347.48, y=58.89, z=147.82], EntityFishCod['Cod'/305, l='MpServer', x=351.54, y=58.84, z=154.85], EntityFishSalmon['Salmon'/306, l='MpServer', x=348.22, y=59.89, z=145.20], EntityFishCod['Cod'/308, l='MpServer', x=349.37, y=62.00, z=143.80], EntityFishCod['Cod'/309, l='MpServer', x=349.40, y=58.81, z=156.20], EntityFishCod['Cod'/310, l='MpServer', x=353.24, y=57.92, z=155.24], EntityFishCod['Cod'/311, l='MpServer', x=347.50, y=62.00, z=197.50], EntityFishCod['Cod'/313, l='MpServer', x=346.04, y=61.18, z=200.50], EntityFishSalmon['Salmon'/314, l='MpServer', x=350.50, y=61.00, z=208.50], EntityFishSalmon['Salmon'/315, l='MpServer', x=349.50, y=61.00, z=210.50], EntityFishSalmon['Salmon'/316, l='MpServer', x=348.49, y=61.31, z=211.56], EntityFishSalmon['Salmon'/317, l='MpServer', x=351.50, y=61.00, z=213.50], EntityFishSalmon['Salmon'/318, l='MpServer', x=351.50, y=61.00, z=211.50], EntityIceCreeper['Creeper de Hielo'/325, l='MpServer', x=361.50, y=40.00, z=62.50], EntityLightCreeper['Creeper de Luz'/326, l='MpServer', x=351.37, y=36.00, z=63.51], EntityLightCreeper['Creeper de Luz'/327, l='MpServer', x=361.17, y=41.00, z=59.55], EntityEarthCreeper['Creeper de Tierra'/328, l='MpServer', x=364.51, y=40.00, z=69.19], EntityItem['item.tile.sapling.oak'/329, l='MpServer', x=354.14, y=84.00, z=78.13], EntityItem['item.tile.sapling.oak'/330, l='MpServer', x=354.75, y=90.00, z=75.82], EntityItem['item.item.minecraft:apple'/331, l='MpServer', x=353.92, y=89.00, z=76.13], EntityItem['item.item.minecraft:apple'/332, l='MpServer', x=355.39, y=88.00, z=74.13], EntityItem['item.tile.sapling.oak'/333, l='MpServer', x=356.67, y=79.00, z=90.00], EntityItem['item.tile.sapling.oak'/335, l='MpServer', x=356.27, y=80.00, z=93.78], EntityItem['item.tile.sapling.oak'/336, l='MpServer', x=355.13, y=80.00, z=89.90], EntityFishCod['Cod'/337, l='MpServer', x=353.63, y=58.85, z=107.16], EntityFishCod['Cod'/338, l='MpServer', x=367.50, y=60.85, z=99.48], EntityFishCod['Cod'/339, l='MpServer', x=363.50, y=62.00, z=98.50], EntityFishCod['Cod'/340, l='MpServer', x=362.50, y=62.00, z=101.96], EntityFishCod['Cod'/341, l='MpServer', x=364.50, y=62.00, z=101.50], EntityFishCod['Cod'/342, l='MpServer', x=355.74, y=61.20, z=151.50], EntityFishCod['Cod'/343, l='MpServer', x=362.39, y=62.15, z=155.52], EntityFishCod['Cod'/344, l='MpServer', x=361.66, y=62.20, z=154.30], EntityFishSalmon['Salmon'/346, l='MpServer', x=351.84, y=62.20, z=213.90], EntityFishSalmon['Salmon'/363, l='MpServer', x=378.56, y=59.33, z=84.36], EntityFishSalmon['Salmon'/364, l='MpServer', x=378.16, y=61.13, z=87.10], EntityFishSalmon['Salmon'/365, l='MpServer', x=370.05, y=62.00, z=102.85], EntityFishSalmon['Salmon'/366, l='MpServer', x=369.77, y=60.81, z=102.37], EntityCakeCreeper['Cake Creeper'/367, l='MpServer', x=371.30, y=35.16, z=139.70], EntitySpiderCreeper['Creeper Araña'/368, l='MpServer', x=368.50, y=36.00, z=137.50], EntityFishCod['Cod'/369, l='MpServer', x=370.67, y=41.33, z=132.50], EntityFishCod['Cod'/370, l='MpServer', x=371.50, y=50.96, z=132.50], EntityFishCod['Cod'/371, l='MpServer', x=371.82, y=49.68, z=132.80], EntityFishCod['Cod'/372, l='MpServer', x=371.01, y=49.96, z=133.19], EntityItem['item.tile.sapling.jungle'/373, l='MpServer', x=382.13, y=98.00, z=150.38], EntityFishSalmon['Salmon'/374, l='MpServer', x=377.77, y=59.00, z=165.53], EntityItem['item.tile.sapling.jungle'/375, l='MpServer', x=381.72, y=77.00, z=161.66], EntityCow['Vaca'/376, l='MpServer', x=380.35, y=67.00, z=189.33], EntityCow['Vaca'/377, l='MpServer', x=370.80, y=67.00, z=188.63], EntityCow['Vaca'/378, l='MpServer', x=380.35, y=65.00, z=200.86], EntityFishSalmon['Salmon'/393, l='MpServer', x=398.50, y=57.00, z=179.50], EntityCow['Vaca'/394, l='MpServer', x=385.21, y=68.00, z=192.13], EntityZombie['Zombi'/395, l='MpServer', x=389.52, y=14.00, z=214.83], EntityFishSalmon['Salmon'/404, l='MpServer', x=400.93, y=62.00, z=55.63], EntityFishCod['Cod'/412, l='MpServer', x=400.50, y=10.00, z=82.50], EntityLightningCreeper['Lightning Creeper'/413, l='MpServer', x=405.50, y=35.00, z=91.50], EntityZombie['Zombi'/160, l='MpServer', x=253.27, y=39.00, z=82.47], EntityZombieCreeper['Zombie Creeper'/162, l='MpServer', x=247.50, y=25.00, z=106.50], EntityCow['Vaca'/163, l='MpServer', x=252.52, y=63.00, z=97.45], EntityCow['Vaca'/164, l='MpServer', x=249.60, y=65.00, z=122.80], EntityCookieCreeper['Creeper Galleta'/165, l='MpServer', x=254.50, y=30.00, z=133.50], EntityCookieCreeper['Creeper Galleta'/166, l='MpServer', x=255.50, y=29.00, z=144.18], EntityFishSalmon['Salmon'/422, l='MpServer', x=406.50, y=61.00, z=188.50], EntityCow['Vaca'/169, l='MpServer', x=249.80, y=65.00, z=157.40], EntityFishSalmon['Salmon'/425, l='MpServer', x=403.54, y=61.00, z=184.70], EntityPsychicCreeper['Creeper Psíquico'/426, l='MpServer', x=401.50, y=17.00, z=196.50], EntitySpiderCreeper['Creeper Araña'/427, l='MpServer', x=402.50, y=17.00, z=205.50], EntityZombie['Zombi'/428, l='MpServer', x=395.57, y=22.00, z=209.19], EntityChicken['Gallina'/173, l='MpServer', x=251.19, y=63.00, z=213.92], EntityCow['Vaca'/430, l='MpServer', x=405.40, y=68.00, z=196.78], EntityChicken['Gallina'/174, l='MpServer', x=251.40, y=62.52, z=209.19], EntitySkeleton['Esqueleto'/177, l='MpServer', x=260.52, y=34.00, z=69.72], EntityHarshenSoul['entity.harshen_soul.name'/178, l='MpServer', x=265.27, y=13.00, z=91.51], EntitySpringCreeper['Spring Creeper'/179, l='MpServer', x=254.59, y=20.00, z=85.79], EntityBallisticCreeper['Ballistic Creeper'/180, l='MpServer', x=271.50, y=34.00, z=91.50], EntityLightningCreeper['Lightning Creeper'/181, l='MpServer', x=256.15, y=30.00, z=132.06], EntityCookieCreeper['Creeper Galleta'/182, l='MpServer', x=255.85, y=30.00, z=131.44], EntityCookieCreeper['Creeper Galleta'/183, l='MpServer', x=258.50, y=30.00, z=128.50], EntityCow['Vaca'/184, l='MpServer', x=258.46, y=66.00, z=153.72], EntityPlayerSP['bvioto'/448, l='MpServer', x=326.59, y=85.00, z=134.38], EntityLatchedRenderer['desconocido'/450, l='MpServer', x=326.59, y=85.00, z=134.38], EntitySkeleton['Esqueleto'/198, l='MpServer', x=286.50, y=21.00, z=84.50], EntityWaterCreeper['Creeper de Agua'/199, l='MpServer', x=276.23, y=39.00, z=97.52], MoCEntityLion['Lion'/201, l='MpServer', x=285.89, y=69.00, z=131.93], EntityCreeper['Creeper'/202, l='MpServer', x=286.50, y=47.00, z=158.50], EntityChicken['Gallina'/203, l='MpServer', x=272.81, y=67.00, z=148.60], EntityFishCod['Cod'/468, l='MpServer', x=269.50, y=62.00, z=73.50], MoCEntitySnake['Snake'/213, l='MpServer', x=298.36, y=65.00, z=74.92], EntityFishCod['Cod'/469, l='MpServer', x=270.50, y=62.00, z=71.50], EntityPsychicCreeper['Creeper Psíquico'/214, l='MpServer', x=292.50, y=38.00, z=94.50], EntityFishCod['Cod'/470, l='MpServer', x=265.50, y=62.00, z=74.50], EntityCookieCreeper['Creeper Galleta'/215, l='MpServer', x=302.50, y=25.00, z=121.50], EntityFishCod['Cod'/471, l='MpServer', x=266.50, y=62.00, z=75.50], EntityCow['Vaca'/216, l='MpServer', x=300.85, y=67.00, z=120.47], EntityFishCod['Cod'/217, l='MpServer', x=289.94, y=42.04, z=132.09], EntityIceCreeper['Creeper de Hielo'/218, l='MpServer', x=297.50, y=37.00, z=140.50], MoCEntityLion['Lion'/219, l='MpServer', x=300.15, y=70.00, z=146.64], EntityChicken['Gallina'/220, l='MpServer', x=289.10, y=66.00, z=157.72], EntityCow['Vaca'/221, l='MpServer', x=296.64, y=67.00, z=157.79], EntityChicken['Gallina'/222, l='MpServer', x=300.22, y=67.00, z=172.50], EntityCow['Vaca'/223, l='MpServer', x=289.52, y=66.00, z=163.82], EntityFishCod['Cod'/224, l='MpServer', x=292.50, y=62.00, z=190.50], EntityFishCod['Cod'/225, l='MpServer', x=293.40, y=62.00, z=191.83], EntityItem['item.item.egg'/226, l='MpServer', x=291.07, y=63.00, z=182.13], EntityChicken['Gallina'/227, l='MpServer', x=292.19, y=64.00, z=182.48], EntityFishSalmon['Salmon'/228, l='MpServer', x=293.50, y=61.00, z=195.50], EntityFishSalmon['Salmon'/229, l='MpServer', x=295.48, y=62.00, z=204.43], EntityFishSalmon['Salmon'/230, l='MpServer', x=297.90, y=62.00, z=202.32], EntityChicken['Gallina'/244, l='MpServer', x=317.13, y=70.00, z=94.58], EntityFishCod['Cod'/245, l='MpServer', x=326.20, y=62.00, z=112.63], EntityZombie['Zombi'/246, l='MpServer', x=309.50, y=22.00, z=209.50], EntityZombie['Zombi'/247, l='MpServer', x=312.50, y=22.00, z=211.32], EntityZombie['Zombi'/248, l='MpServer', x=311.50, y=22.00, z=214.50], EntityStoneCreeper['Creeper de Piedra'/249, l='MpServer', x=311.50, y=22.00, z=212.50], EntityItem['item.item.minecraft:apple'/765, l='MpServer', x=345.83, y=85.00, z=74.40]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2090049888 bytes (1993 MB) / 5234491392 bytes (4992 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 106
	FML: MCP 9.42 Powered by Forge 14.23.2.2629 Optifine OptiFine_1.12.2_HD_U_C9 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version         | Source                                        | Signature                                |
	|:--------- |:-------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                  | 9.42            | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99       | forge-1.12.2-14.23.2.2629.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.2.2629    | forge-1.12.2-14.23.2.2629.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy    | 1.0.0           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | itemphysic           | 1.4.0           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mercurius_updater    | 1.0             | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | uncraftingtable      | 1.8-beta6       | [1.12]UncraftingTable-1.8-beta6.jar           | None                                     |
	| UCHIJAAAA | actuallyadditions    | 1.12.2-r132     | ActuallyAdditions-1.12.2-r132.jar             | None                                     |
	| UCHIJAAAA | psi                  | r1.1-59         | Psi-r1.1-59.jar                               | None                                     |
	| UCHIJAAAA | autoreglib           | 1.3-15          | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCHIJAAAA | betterfoliage        | 2.1.10          | BetterFoliage-MC1.12-2.1.10.jar               | None                                     |
	| UCHIJAAAA | biomesoplenty        | 7.0.1.2325      | BiomesOPlenty-1.12.2-7.0.1.2325-universal.jar | None                                     |
	| UCHIJAAAA | birdsfoods           | 2.5 [1.12]      | Birds-Foods-Mod-1.12.jar                      | None                                     |
	| UCHIJAAAA | carryon              | 1.7.2           | CarryOn+MC1.12.2+v1.7.2.jar                   | None                                     |
	| UCHIJAAAA | chameleon            | 1.12-4.1.3      | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHIJAAAA | charcoal_pit         | 1.9             | CharcoalPit-[1.12]-1.9.jar                    | None                                     |
	| UCHIJAAAA | coffeespawner        | 1.0.2           | Coffee-Spawner-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | cookingforblockheads | 6.3.17          | CookingForBlockheads_1.12.1-6.3.17.jar        | None                                     |
	| UCHIJAAAA | coralreef            | 2.0             | CoralReef-2.2-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | craftelytra          | 1.2             | Craftable-Elytra-Mod-1.12.2.jar               | None                                     |
	| UCHIJAAAA | craftingtweaks       | 8.1.6           | CraftingTweaks_1.12.1-8.1.6.jar               | None                                     |
	| UCHIJAAAA | creativecore         | 1.9.9           | CreativeCore+v1.9.14+mc1.12.2.jar             | None                                     |
	| UCHIJAAAA | defiledlands         | 1.2.0           | Defiled-Lands-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | elementalcreepers    | v4.1.gf82c179   | ElementalCreepers-v4.1.gf82c179.jar           | None                                     |
	| UCHIJAAAA | endercrop            | 1.12-1.3.4      | endercrop-1.12-1.3.4.jar                      | None                                     |
	| UCHIJAAAA | gardenstuff          | 1.12-2.1.0      | GardenStuff-1.12-2.1.0.jar                    | None                                     |
	| UCHIJAAAA | harshencastle        | 0.13.1          | Harshen-Castle-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | waila                | 1.8.20          | Hwyla-1.8.20-B35_1.12.jar                     | None                                     |
	| UCHIJAAAA | ichunutil            | 7.1.4           | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHIJAAAA | ic2                  | 2.8.16-ex112    | Industrialcraft-1.12.jar                      | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | ironbackpacks        | 1.12.2-3.0.5-6  | IronBackpacks-1.12.2-3.0.5-6.jar              | None                                     |
	| UCHIJAAAA | jei                  | 4.8.5.159       | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2    | JourneyMap-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | jukebox              | 1.2             | jukebox-1.2.jar                               | None                                     |
	| UCHIJAAAA | jaff                 | 1.7_for_1.12    | JustAFewFish-1.7_for_1.12.jar                 | None                                     |
	| UCHIJAAAA | justenoughbuttons    | 1.12-1.2.1      | justenoughbuttons-1.12-1.2.1.jar              | None                                     |
	| UCHIJAAAA | magipsi              | 1.3             | MagicalPsi-1.3.jar                            | None                                     |
	| UCHIJAAAA | magicclover          | 1.12-0.7.8      | magicclover-1.12-0.7.8.jar                    | None                                     |
	| UCHIJAAAA | mantle               | 1.12-1.3.1.21   | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHIJAAAA | mocreatures          | 12.0.3          | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | tconstruct           | 1.12.2-2.9.1.65 | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UCHIJAAAA | moartinkers          | 0.5.4           | moartinkers-0.5.4.jar                         | None                                     |
	| UCHIJAAAA | mobdismemberment     | 7.0.0           | MobDismemberment-1.12.2-7.0.0.jar             | None                                     |
	| UCHIJAAAA | modernlamps          | 1.0.3           | ModernLights-1.0.3_1.12.jar                   | None                                     |
	| UCHIJAAAA | openglider           | @VERSION@       | OpenGlider-1.12.1-1.1.0.jar                   | None                                     |
	| UCHIJAAAA | oreexcavation        | 1.4.113         | OreExcavation-1.4.113.jar                     | None                                     |
	| UCHIJAAAA | morepaintings        | $version        | paintings-1.12.2-3.3.0.0.jar                  | None                                     |
	| UCHIJAAAA | guilib               | $version        | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar | None                                     |
	| UCHIJAAAA | paintingselgui       | $version        | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar | None                                     |
	| UCHIJAAAA | harvestcraft         | 1.12.2q         | Pam's+HarvestCraft+1.12.2q.jar                | None                                     |
	| UCHIJAAAA | personalcars         | 1.4             | PersonalCars-1.4.jar                          | None                                     |
	| UCHIJAAAA | placeableitems       | 3.2             | placeableitems-3.2.jar                        | None                                     |
	| UCHIJAAAA | placebo              | 1.3.1           | Placebo-1.12.2-1.3.1.jar                      | None                                     |
	| UCHIJAAAA | plants2              | 2.6.4           | Plants-Mod-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | portalgun            | 7.0.2           | PortalGun-1.12.2-7.0.2.jar                    | None                                     |
	| UCHIJAAAA | reborncore           | 3.6.11.220      | RebornCore-1.12.2-3.6.11.220-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | rustic               | 1.0.2           | rustic-1.0.2.jar                              | None                                     |
	| UCHIJAAAA | scannable            | 1.6.2.13        | Scannable-MC1.12-1.6.2.13.jar                 | None                                     |
	| UCHIJAAAA | soundfilters         | 0.10_for_1.12   | SoundFilters-0.10_for_1.12.jar                | None                                     |
	| UCHIJAAAA | stevescarts          | 2.4.18.92       | StevesCarts-1.12.2-2.4.18.92.jar              | None                                     |
	| UCHIJAAAA | storagedrawers       | 1.12-5.2.5      | StorageDrawers-1.12.2-5.3.5.jar               | None                                     |
	| UCHIJAAAA | toroquest            | 1.12.2-5.2      | toroquest-1.12.2-5.2.jar                      | None                                     |
	| UCHIJAAAA | tropicraft           | 7.1.0.50        | tropicraft-MC1.12.2-7.1.0.50.jar              | None                                     |
	| UCHIJAAAA | waddles              | 0.5.6           | Waddles-1.12.2-0.5.6.jar                      | None                                     |
	| UCHIJAAAA | wawla                | 2.5.253         | Wawla-1.12.2-2.5.253.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
CreativePatchingLoader (CreativeCore+v1.9.14+mc1.12.2.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ItemPatchingLoader (ItemPhysic+Full+1.4.10+mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.6.11.220
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2629
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.43, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: paper_cutout_3_71859379.zip
	Current Language: Español (México)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL Standard v6.2.zip
	OpenGlVersion: 4.6.0 NVIDIA 388.43
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by tterrag1098** [comment]
Look in the crash-reports folder.

**Comment by Bvioto** [comment]
I already posted it

**Comment by Cojomax99** [comment]
Thank you! The problem has been located and will be fixed in the next released version of 1.12.2

**Comment by Bvioto** [comment]
Ok, thank you. I love this mod and I want to use it :(

**Comment by Cojomax99** [comment]
This is now fixed in https://minecraft.curseforge.com/projects/tropicraft/files/2543037. Closing :)
