### ISSUE TITLE
Crash: java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.

### ISSUE THREAD

**Issue by hxz355** [Tropicraft/Tropicraft#264]
## Issue Description

The game crash while loading.

java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.

## Steps to Reproduce
1) Please go to: http://openeye.openmods.info/crashes/d124cfec57723e60ae5b40c0324b70a5 to see more details.
2) I'm pretty sure that the game crash when installing mod 'Galacticraft Add-on - More Planets' (https://minecraft.curseforge.com/projects/galacticraft-add-on-more-planets) the same time.

Tropicraft Version:   1.12.2-7.1.3.62
Forge Version:   14.23.2.2654

## Crash log
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tropicraft (tropicraft)

Caused by..

java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.

    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:289)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:275)
    at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:108)
    at net.tropicraft.core.common.biome.BiomeTropicraft.registerBiomes(BiomeTropicraft.java:56)
    at net.tropicraft.Tropicraft.init(Tropicraft.java:110)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
    at sun.reflect.GeneratedMethodAccessor.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by tterrag1098** [comment]
You have too many mods adding biomes, and you're out of IDs. This is not a Tropicraft issue, and furthermore we only add a handful of biomes.

**Comment by Danielx40** [comment]
normaly this can be fix with not enough id  but not always

**Comment by SolMace** [comment]
> normaly this can be fix with not enough id but not always

is there any way to fix it by holding onto the mods adding so many new biomes? or no cause id like to keep my mods and still fix the issue I also have NEids on and it didn't help

**Comment by SolMace** [comment]
> You have too many mods adding biomes, and you're out of IDs. This is not a Tropicraft issue, and furthermore we only add a handful of biomes.

is there a way to have all the biome mods and still run it normally

**Comment by NotActuallyTerry** [comment]
Your best bet would be trying to use Not Enough IDs, a coremod that expands the amount of IDs that can be used by things. https://www.curseforge.com/minecraft/mc-mods/notenoughids

**Comment by sorukohi** [comment]
@hxz355 @MystiLV5
Hi! Did you find the answer? Also have the NEIDs, but it don't help :(
