### ISSUE TITLE
Server crashes when I go to Tropical dimension 

### ISSUE THREAD

**Issue by stefan-asf** [Tropicraft/Tropicraft#265]
## Issue Description
I have last version of this mod for Minecraft 1.12.2, every time when I go to tropical dimension server crashes  

## Steps to Reproduce
1) Fix this awful bug
2) ??
3) ??

Tropicraft Version: latest: 7.1.3.62
Forge Version: 2694

## Crash log
`` 

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/8/18 10:47 PM
Description: Ticking entity

java.lang.NoClassDefFoundError: javax/vecmath/Vector2f
	at net.tropicraft.core.common.entity.underdasea.atlantoku.EntityTropicraftWaterBase.setTargetHeading(EntityTropicraftWaterBase.java:568)
	at net.tropicraft.core.common.entity.underdasea.atlantoku.EntityTropicraftWaterBase.setRandomTargetHeading(EntityTropicraftWaterBase.java:502)
	at net.tropicraft.core.common.entity.underdasea.atlantoku.ai.EntityAISwimTargetPrey.func_75246_d(EntityAISwimTargetPrey.java:108)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.tropicraft.core.common.entity.underdasea.atlantoku.EntityTropicraftWaterBase.func_70636_d(EntityTropicraftWaterBase.java:130)
	at net.tropicraft.core.common.entity.underdasea.atlantoku.EntitySchoolableFish.func_70636_d(EntitySchoolableFish.java:58)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Vector2f
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.tropicraft.core.common.entity.underdasea.atlantoku.EntityTropicraftWaterBase.setTargetHeading(EntityTropicraftWaterBase.java:568)
	at net.tropicraft.core.common.entity.underdasea.atlantoku.EntityTropicraftWaterBase.setRandomTargetHeading(EntityTropicraftWaterBase.java:502)
	at net.tropicraft.core.common.entity.underdasea.atlantoku.ai.EntityAISwimTargetPrey.func_75246_d(EntityAISwimTargetPrey.java:108)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.tropicraft.core.common.entity.underdasea.atlantoku.EntityTropicraftWaterBase.func_70636_d(EntityTropicraftWaterBase.java:130)
	at net.tropicraft.core.common.entity.underdasea.atlantoku.EntitySchoolableFish.func_70636_d(EntitySchoolableFish.java:58)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: tropicraft:piranha (net.tropicraft.core.common.entity.underdasea.atlantoku.EntityPiranha)
	Entity ID: 677
	Entity Name: Piranha
	Entity's Exact location: 82.50, 56.00, 148.50
	Entity's Block location: World: (82,56,148), Chunk: (at 2,3,4 in 5,9; contains blocks 80,0,144 to 95,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['ribasDC'/444, l='world', x=21.00, y=66.50, z=260.00]]
	Chunk stats: ServerChunkCache: 374 Drop: 0
	Level seed: -9183276025688142535
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 3.0.6-gentoo
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 654094096 bytes (623 MB) / 1055850496 bytes (1006 MB) up to 1583808512 bytes (1510 MB)
	JVM Flags: 11 total; -Xms1024M -Xmx1536M -XX:ParallelGCThreads=1 -XX:PermSize=256m -XX:NewRatio=5 -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:UseSSE=3 -XX:MaxGCPauseMillis=500 -Xverify:none
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 50
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                             | Signature                                |
	|:--------- |:------------------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                      | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                      | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | craftbukkit.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.2.2611 | craftbukkit.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | campfire            | 1.2          | campfire_1.12_v1.2.jar             | None                                     |
	| UCHIJAAAA | cucumber            | 1.1.0        | cucumber-1.12-1.1.0.jar            | None                                     |
	| UCHIJAAAA | jei                 | 4.8.5.159    | jei_1.12.2_4.8.5.159 (1).jar       | None                                     |
	| UCHIJAAAA | ftblib              | 5.0.0.14     | FTBLib-1.12.2-5.0.0.14.jar         | None                                     |
	| UCHIJAAAA | mysticalagriculture | 1.6.9        | mysticalagriculture-1.12-1.6.9.jar | None                                     |
	| UCHIJAAAA | quickget            | 1.0          | quickget_1.0.jar                   | None                                     |
	| UCHIJAAAA | signpost            | 1.07.2       | signpost_1.12_1.07.2.jar           | None                                     |
	| UCHIJAAAA | subterranaenwaters  | 1.12.2-1.0   | subh2o_1.12.2_1.0.jar              | None                                     |
	| UCHIJAAAA | tropicraft          | 7.1.3.62     | tropicraft-MC1.12.2-7.1.3.62.jar   | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 15; [EntityPlayerMP['ribasDC'/444, l='world', x=21.00, y=66.50, z=260.00]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by tterrag1098** [comment]
Hi, your server installation seems to be missing some critical libraries. Did you run the forge installer on your server, or just copy files to it?

**Comment by stefan-asf** [comment]
Hello. I’ve installed the forge in folder, setted up the whole server too. Then I put everything on my host and BAM, crash. Everything works nice in single player. Maybe I’ll reinstall forge, but I don’t think it will help.

**Comment by tterrag1098** [comment]
Could you also try updating forge to latest?

**Comment by stefan-asf** [comment]
Okay, I’ll try it, but I don’t think it will work.

**Comment by kencinder** [comment]
Latest Forge isn't always the answer, in fact I'm seeing a LOT of people with problems because of it. IMO stick to 2611 unless you have a mod that NEEDS something higher than recommended, otherwise you're rolling the dice.
