### ISSUE TITLE
Biome crash

### ISSUE THREAD

**Issue by katsoa** [Tropicraft/Tropicraft#275]
## Issue Description
Basically this happens whenever i try to move around in the tropicraft dimension, specifically the rain forest, it doesn't crash right away but i haven't seen any other threads on the crash I'm getting.

Tropicraft Version:   Newest current vers. (1.12.2-7.1.3.62)
Forge Version:  1.12.2-14.23.3.2655

## Crash log
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.3-1.12.2.jar)
  llibrary (LLibrary-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 5/1/18 9:12 PM
Description: Exception ticking world

java.lang.ClassCastException: com.gildedgames.aether.common.world.util.BiomeInstancedZone cannot be cast to net.tropicraft.core.common.biome.BiomeTropicraft
	at net.tropicraft.core.common.dimension.ChunkProviderTropicraft.func_185931_b(ChunkProviderTropicraft.java:80)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:978)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.tropicraft.core.common.dimension.ChunkProviderTropicraft.func_185931_b(ChunkProviderTropicraft.java:80)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:978)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: h
	All players: 1 total; [EntityPlayerMP['Katoasumas'/4896, l='h', x=-342.33, y=99.72, z=161.50]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: 3158592221841059170
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 977366792 bytes (932 MB) / 3187671040 bytes (3040 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 49
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 Optifine OptiFine_1.12.2_HD_U_D1 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                               | Signature                                |
	|:--------- |:----------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.3.2655.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.3.2655 | forge-1.12.2-14.23.3.2655.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | obfuscate         | 0.2.3        | minecraft.jar                        | None                                     |
	| UCHIJAAAA | orbis_api         | 1.12.2-1.0.0 | Orbis-API-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | aether            | 1.12.2-1.0.0 | Aether-2-Mod-1.12.2.jar              | None                                     |
	| UCHIJAAAA | aether_legacy     | v1.0         | Aether-Legacy-Mod-1.12.2.jar         | None                                     |
	| UCHIJAAAA | craftstudioapi    | 1.0.0        | CraftStudio-API-1.12.1.jar           | None                                     |
	| UCHIJAAAA | animania          | 1.4.7        | animania-1.12.2-1.4.7.jar            | None                                     |
	| UCHIJAAAA | battletowers      | 1.6.1        | BattleTowers-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | bibliocraft       | 2.4.3        | BiblioCraft[v2.4.3][MC1.12.0].jar    | None                                     |
	| UCHIJAAAA | ceramics          | 1.12-1.3.4   | Ceramics-1.12-1.3.4.jar              | None                                     |
	| UCHIJAAAA | cfm               | 4.2.0        | cfm-4.2.0-mc1.12.2.jar               | None                                     |
	| UCHIJAAAA | cgm               | 0.2.1        | cgm-0.2.1-mc1.12.2.jar               | None                                     |
	| UCHIJAAAA | chameleon         | 1.12-4.1.3   | Chameleon-1.12-4.1.3.jar             | None                                     |
	| UCHIJAAAA | customspawner     | 3.11.4       | CustomMobSpawner-3.11.4.jar          | None                                     |
	| UCHIJAAAA | ptrmodellib       | 1.0.0        | DecoCraft-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | props             | 2.5.4        | DecoCraft-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | mocreatures       | 12.0.4       | DrZharks MoCreatures Mod-12.0.4.jar  | None                                     |
	| UCHIJAAAA | fairylights       | 2.1.1        | Fairy-Lights-Mod-1.12.jar            | None                                     |
	| UCHIJAAAA | gravestone        | 1.0.12       | Gravestone-Mod-1.12.jar              | None                                     |
	| UCHIJAAAA | ichunutil         | 7.1.4        | iChun-Util-Mod-1.12.2.jar            | None                                     |
	| UCHIJAAAA | gravitygun        | 7.0.0        | Gravity-Gun-Mod-1.12.2.jar           | None                                     |
	| UCHIJAAAA | harvestcraft      | 1.12.2o      | HarvestCraft-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | llibrary          | 1.7.7        | LLibrary-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | iceandfire        | 1.3.1        | Ice-and-Fire-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | hats              | 7.0.0        | iChuns-Hats-Mod-1.12.2.jar           | None                                     |
	| UCHIJAAAA | inventorypets     | 1.4.9.9b     | inventorypets-1.12-1.4.9.9b.jar      | None                                     |
	| UCHIJAAAA | jei               | 4.8.5.159    | Just-Enough-Items-Mod-1.12.2.jar     | None                                     |
	| UCHIJAAAA | mystic            | 0.5.0        | Kether-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | lucky             | 7.5.0        | Lucky-Block-Mod-1.12.zip             | None                                     |
	| UCHIJAAAA | radixcore         | 1.12.x-2.2.1 | RadixCore-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | mca               | 1.12.2-5.3.1 | Minecraft-Comes-Alive-Mod-1.12.2.jar | None                                     |
	| UCHIJAAAA | morph             | 7.1.0        | Morphing-Mod-1.12.2.jar              | None                                     |
	| UCHIJAAAA | cdm               | 0.3.1        | MrCrayfishs-Device-Mod-1.12.2.jar    | None                                     |
	| UCHIJAAAA | redstoneflux      | 2.0.1        | RedstoneFlux-1.12.2.jar              | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | storagedrawers    | 1.12-5.3.5   | StorageDrawers-1.12.2-5.3.6.jar      | None                                     |
	| UCHIJAAAA | stupidthings      | 1.1.5        | Stupid-Things-Mod-1.12.2.jar         | None                                     |
	| UCHIJAAAA | bspkrscore        | at_0.9       | TreeCapitator-Mod-1.12.jar           | None                                     |
	| UCHIJAAAA | treecapitator     | at_0.9       | TreeCapitator-Mod-1.12.jar           | None                                     |
	| UCHIJAAAA | tropicraft        | 7.1.3.62     | tropicraft-MC1.12.2-7.1.3.62.jar     | None                                     |
	| UCHIJAAAA | car               | 1.2.11       | Ultimate-Car-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | wearablebackpacks | 3.1.0        | Wearable-Backpacks-Mod-1.12.2.jar    | None                                     |
	| UCHIJAAAA | weeeflowers       | 1.12.2a      | Weee-Flowers-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | xaerominimap      | 1.15         | Xaeros_Minimap_1.15_Forge_1.12.jar   | None                                     |
	| UCHIJAAAA | elulib            | 0.1.7        | EluLib-1.12.2.jar                    | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.2.3-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
llibrary (LLibrary-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)

```
**yes, i do have mods, but i tried loading it again with no mods in the same area and got a similar crash**
## Crash log
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 5/1/18 9:24 PM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.world.biome.BiomePlains cannot be cast to net.tropicraft.core.common.biome.BiomeTropicraft
	at net.tropicraft.core.common.dimension.ChunkProviderTropicraft.func_185931_b(ChunkProviderTropicraft.java:80)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:106)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 238159280 bytes (227 MB) / 721420288 bytes (688 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 1, tcache: 34, allocated: 1, tallocated: 50
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version      | Source                           | Signature                                |
	|:--------- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.3.2655.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.3.2655 | forge-1.12.2-14.23.3.2655.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | tropicraft | 7.1.3.62     | tropicraft-MC1.12.2-7.1.3.62.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Katoasumas'/88, l='h', x=-342.33, y=99.72, z=161.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

```

sorry if it's an obvious issue or something that i'm not seeing

**Comment by NotActuallyTerry** [comment]
Closing, please discuss this under #314
