### ISSUE TITLE
NEI Cheat Mode Crash

### ISSUE THREAD

**Issue by downslope7** [Tropicraft/Tropicraft#35]
In NEI Cheat Mode, click one of the chairs to get one and you crash with this:

```
java.lang.NoSuchMethodError: net.tropicraft.item.ItemTropicraftColored.func_111208_A()Ljava/lang/String;
        at net.tropicraft.item.ItemTropicraftColored.func_77653_i(ItemTropicraftColored.java:80) ~[ItemTropicraftColored.class:?]
        at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
        at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:759) ~[add.class:?]
        at codechicken.nei.NEIServerUtils.givePlayerItem(NEIServerUtils.java:189) ~[NEIServerUtils.class:?]
        at codechicken.nei.NEISPH.handleGiveItem(NEISPH.java:143) ~[NEISPH.class:?]
        at codechicken.nei.NEISPH.handlePacket(NEISPH.java:34) ~[NEISPH.class:?]
        at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:115) ~[PacketCustom$ServerInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
        at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by medsouz** [comment]
I could not reproduce the issue with MinecraftForge v10.13.2.1231, NotEnoughItems-1.7.10-1.0.3.74, and Tropicraft-6.0.3.

**Comment by medsouz** [comment]
Oh, it only happens you're running a dedicated server.

Fixed :smile:
