### ISSUE TITLE
Game crashes after opening the mod's menu (creative)

### ISSUE THREAD

**Issue by NEicke0** [Tropicraft/Tropicraft#354]
## Issue Description
Everytime I open the mod menu crashes, apparently one item isn't rendering right

## Steps to Reproduce
1)Open world
2)Go to the mod's creative menu
3)Slide down and then crashes

Tropicraft Version:   7.1.9.115
Forge Version:   1.12.2-14.23.5.2768

## Crash log
```
PASTE YOUR CRASH LOG HERE
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LibrarianLib Plugin (librarianlib-4.0.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 12/27/19 1:35 PM
Description: Rendering item

java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.lambda$handleItemState$0(AbstractCTMBakedModel.java:113)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides$$Lambda$719/1449327553.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.handleItemState(AbstractCTMBakedModel.java:113)
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.call(Reflector.java:955)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:398)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:549)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.callVoid(Reflector.java:648)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.lambda$handleItemState$0(AbstractCTMBakedModel.java:113)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides$$Lambda$719/1449327553.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.handleItemState(AbstractCTMBakedModel.java:113)
	at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.call(Reflector.java:955)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:398)

-- Item being rendered --
Details:
	Item Type: net.tropicraft.core.common.itemblock.ItemBlockTropicraft@704b6c7f
	Item Aux: 1
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:549)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.callVoid(Reflector.java:648)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (358, 186). Absolute: (1075, 493)
	Screen size: Scaled: (640, 351). Absolute: (1920, 1051). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Nick_olas'/78, l='MpServer', x=-1468.50, y=4.00, z=-261.50]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1469,4,-259), Chunk: (at 3,0,13 in -92,-17; contains blocks -1472,0,-272 to -1457,255,-257), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Level time: 1639 game time, 1639 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 24 total; [EntitySlime['Slime'/33, l='MpServer', x=-1542.41, y=4.34, z=-254.99], EntitySlime['Slime'/34, l='MpServer', x=-1547.65, y=4.00, z=-259.30], EntitySlime['Slime'/35, l='MpServer', x=-1545.46, y=4.00, z=-243.06], Gaur, Gaur, EntitySlime['Slime'/45, l='MpServer', x=-1531.07, y=5.17, z=-267.45], EntitySlime['Slime'/46, l='MpServer', x=-1526.41, y=4.00, z=-241.18], EntitySlime['Slime'/47, l='MpServer', x=-1530.71, y=4.61, z=-229.31], EntitySlime['Slime'/79, l='MpServer', x=-1476.35, y=4.00, z=-312.17], EntitySlime['Slime'/48, l='MpServer', x=-1528.23, y=4.00, z=-237.96], African Lion, EntitySlime['Slime'/49, l='MpServer', x=-1521.55, y=4.00, z=-242.90], African Lion, African Lion, African Lion, EntitySlime['Slime'/87, l='MpServer', x=-1453.35, y=4.00, z=-330.76], EntityPlayerSP['Nick_olas'/78, l='MpServer', x=-1468.50, y=4.00, z=-261.50], EntitySlime['Slime'/56, l='MpServer', x=-1508.99, y=4.08, z=-220.20], Gaur, Gaur, Bengal Tiger, EntitySlime['Slime'/27, l='MpServer', x=-1545.95, y=5.25, z=-341.34], Bengal Tiger, EntitySlime['Slime'/31, l='MpServer', x=-1534.61, y=4.67, z=-323.19]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1743814488 bytes (1663 MB) / 3825205248 bytes (3648 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_D3 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version           | Source                                        | Signature                                |
	|:--------- |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | architecturecraft   | @VERSION@         | architecturecraft-1.12-2.68.jar               | None                                     |
	| UCHIJAAAA | bamboozled          | 1.0.10            | Bamboozled-1.12-1.0.10.jar                    | None                                     |
	| UCHIJAAAA | bibliocraft         | 2.4.3             | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCHIJAAAA | biomesoplenty       | 7.0.1.2387        | BiomesOPlenty-1.12.2-7.0.1.2387-universal.jar | None                                     |
	| UCHIJAAAA | biomestaff          | 1.0.0             | BiomeStaff-1.12.2-1.0.0.jar                   | None                                     |
	| UCHIJAAAA | bookworm            | 1.12.2-2.3.0      | bookworm-1.12.2-2.3.0.jar                     | None                                     |
	| UCHIJAAAA | catwalks            | 1.12.2-4.0.44     | catwalks-1.12.2-4.0.44.jar                    | None                                     |
	| UCHIJAAAA | ctm                 | MC1.12-0.2.3.12   | CTM-MC1.12-0.2.3.12.jar                       | None                                     |
	| UCHIJAAAA | chisel              | MC1.12.2-0.2.0.31 | Chisel-MC1.12.2-0.2.0.31.jar                  | None                                     |
	| UCHIJAAAA | chiselsandbits      | 14.19             | chiselsandbits-14.19 (1).jar                  | None                                     |
	| UCHIJAAAA | ptrmodellib         | 1.0.4             | PTRLib-1.0.4.jar                              | None                                     |
	| UCHIJAAAA | props               | 2.6.3             | Decocraft-2.6.3_1.12.2.jar                    | None                                     |
	| UCHIJAAAA | fairylights         | 2.1.9             | fairylights-2.1.9-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | ferdinandsflowers   | 1.10.1b           | Ferdinand's+Flowers-1.10.1b-1.12.jar          | None                                     |
	| UCHIJAAAA | forgelin            | 1.6.0             | Forgelin-1.6.0.jar                            | None                                     |
	| UCHIJAAAA | cfm                 | 6.3.1             | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | librarianlib        | 4.0               | librarianlib-4.0.jar                          | None                                     |
	| UCHIJAAAA | malisiscore         | 1.12.2-6.4.0      | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCHIJAAAA | malisisdoors        | 1.12.2-7.3.0      | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCHIJAAAA | modernlamps         | 1.0.3             | ModernLights-1.0.3_1.12.jar                   | None                                     |
	| UCHIJAAAA | moon-core           | 7.0               | moon-core_7.0_1.12.jar                        | None                                     |
	| UCHIJAAAA | zawa                | 1.12.2-1.7.0      | zawa-1.12.2-1.7.0.jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| UCHIJAAAA | faunanatural        | 1.12.2-1.5.0      | NaturalFauna+Mod-1.12.2-1.5.0.jar             | None                                     |
	| UCHIJAAAA | harvestcraft        | 1.12.2u           | Pam's+HarvestCraft+1.12.2u.jar                | None                                     |
	| UCHIJAAAA | pmp                 | 1.12.0            | pmp-1.12.0.jar                                | None                                     |
	| UCHIJAAAA | tropicraft          | 7.1.9.115         | tropicraft-MC1.12.2-7.1.9.115 (1).jar         | None                                     |
	| UCHIJAAAA | worldedit           | 6.1.8             | worldedit-forge-mc1.12-6.1.8-dist.jar         | None                                     |
	| UCHIJAAAA | zoocraftdiscoveries | 1.0               | Zoocraft+Discoveries+1.12.2-1.1.0.jar         | None                                     |
	| UCHIJAAAA | librarianliblate    | 4.0               | librarianlib-4.0.jar                          | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ForgelinPlugin (Forgelin-1.6.0.jar)
  
LibrarianLib Plugin (librarianlib-4.0.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.94' Renderer: 'GeForce GTX 1650/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.94, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.22 Medium.zip
	OpenGlVersion: 4.6.0 NVIDIA 431.94
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by tterrag1098** [comment]
Update CTM. Not a Tropicraft issue.
