### ISSUE TITLE
Incompatibility between Tropicraft and The Seasons Mod (Unknown biome exception crash)

### ISSUE THREAD

**Issue by BikeAndGame** [Tropicraft/Tropicraft#385]
Hello, guys. First I'm sorry if the topic is not for here 
If so please moderator move it! I have a problem with the mods in the title. When I want to go in the Tropics DIM the game stops and crashes! (crash report below). Is there any fix  or not to bother? Because I love both of the mods . I read that the seasons mod **IS** compatible with mods that add biomes and crops like Biomes 'O Plenty, HarvestCraft etc. Tropicraft also adds biomes..... I tried to change the IDs of the biomes in tropicraft config but noting changed. I'll be thankfull for yor help have I nice day/night

Here is the latest log
[LatestLog.log](https://github.com/Tropicraft/Tropicraft/files/5898706/LatestLog.log)

Here are the versions of the mod and forge

Tropicraft Version: tropicraft-6.0.5   
Forge Version: Forge10.13.4.1614

As you can see Version of MC is 1.7.10

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/30/21 10:43 PM
Description: Unexpected error

weatherpony.seasons.world.crop.BiomeSettings$Seasons_UnknownBiomeException: Tropics, ID=61, net.tropicraft.world.biomes.BiomeGenTropics@382c279e
	at weatherpony.seasons.world.ClientWorld.getNewTemp(ClientWorld.java:427)
	at weatherpony.seasons.pml.edits.world.biome.BiomeGenBaseEdits$GetFloatTemperature.call2(BiomeGenBaseEdits.java:135)
	at weatherpony.seasons.pml.edits.world.biome.BiomeGenBaseEdits$GetFloatTemperature.call2(BiomeGenBaseEdits.java:94)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:75)
	at weatherpony.partial.HookListenerHelper.distribute(HookListenerHelper.java:64)
	at weatherpony.partial.HookListenerHelperPool.distribute(HookListenerHelperPool.java:134)
	at weatherpony.partial.internal.GeneralHookManager.rigAndDistributeCall(GeneralHookManager.java:276)
	at net.minecraft.world.biome.BiomeGenBase.func_150564_a(BiomeGenBase.java)
	at net.minecraftforge.client.ForgeHooksClient.getSkyBlendColour(ForgeHooksClient.java:408)
	at net.minecraft.world.World.getSkyColorBody(World.java:1597)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:399)
	at net.minecraft.world.World.func_72833_a(World.java:1575)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1672)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1154)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at weatherpony.seasons.world.ClientWorld.getNewTemp(ClientWorld.java:427)
	at weatherpony.seasons.pml.edits.world.biome.BiomeGenBaseEdits$GetFloatTemperature.call2(BiomeGenBaseEdits.java:135)
	at weatherpony.seasons.pml.edits.world.biome.BiomeGenBaseEdits$GetFloatTemperature.call2(BiomeGenBaseEdits.java:94)
	at weatherpony.partial.CallWrapper.call(CallWrapper.java:52)
	at weatherpony.partial.HookListenerHelper.callNext(HookListenerHelper.java:75)
	at weatherpony.partial.HookListenerHelper.distribute(HookListenerHelper.java:64)
	at weatherpony.partial.HookListenerHelperPool.distribute(HookListenerHelperPool.java:134)
	at weatherpony.partial.internal.GeneralHookManager.rigAndDistributeCall(GeneralHookManager.java:276)
	at net.minecraft.world.biome.BiomeGenBase.func_150564_a(BiomeGenBase.java)
	at net.minecraftforge.client.ForgeHooksClient.getSkyBlendColour(ForgeHooksClient.java:408)
	at net.minecraft.world.World.getSkyColorBody(World.java:1597)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:399)
	at net.minecraft.world.World.func_72833_a(World.java:1575)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1672)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1154)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['GloriousMarto'/29, l='MpServer', x=8.50, y=66.62, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['GloriousMarto'/29, l='MpServer', x=8.50, y=66.62, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge,pml
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at weatherpony.pml.premain.ReplacementMainThread.run(ReplacementMainThread.java:104)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1870439200 bytes (1783 MB) / 2260205568 bytes (2155 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 11, allocated: 1, tallocated: 47
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	mcpml{10.1} [Partial Modification Loader [for Minecraft]] (PML_MinecraftApp.jar) 
	UCHIJAAAA	seasonsmod{pre-3.0beta13d5} [The Seasons Mod] ([1.7.10]TheSeasonsMod-pre-3.0beta13d5.jar) 
	UCHIJAAAA	seasonsmodac{1.0} [Additional Seasons Content] ([1.7.10]TheSeasonsMod-pre-3.0beta13d5.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.503.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.503.jar) 
	UCHIJAAAA	tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 460.89' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge,pml'
	Type: Client (map_client.txt)
	Resource Packs: [msi_conversion Updated.zip, Anoyths 3D Animated Localized Weather Mod Texture Pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by NotActuallyTerry** [comment]
We're unable to help, as we haven't updated the 1.7.10 build in 5 years. Sorry about that!
