### ISSUE TITLE
Replay mod loading replay in 1.12.2

### ISSUE THREAD

**Issue by MrBearLoL** [Tropicraft/Tropicraft#433]
## Issue Description
I have a problem with using tropicraft and replay mod. I can record the game with replay mod, but once I try to open the replay file in the replay viewer, it doesn't doing anything.

I saw a post where this has been fixed, but as I saw it's not fixed in any of the 1.12.2 versions... :( 

## Steps to Reproduce
1) Play the game with replay mod recording
2) Exit and open replay viewer
3) Load replay, nothing happens

Tropicraft Version:   tropicraft-MC1.12.2-7.1.9.115   
Forge Version:   1.12.2-forge-14.23.5.2860   

## Crash log
```
[17:27:00] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot load encyclopedia outside of a game!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalStateException: Cannot load encyclopedia outside of a game!
	at net.tropicraft.core.encyclopedia.TropicalBook.getSaveFile(TropicalBook.java:88) ~[TropicalBook.class:?]
	at net.tropicraft.core.encyclopedia.TropicalBook.loadData(TropicalBook.java:104) ~[TropicalBook.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_606_TropicalBook_loadData_Load.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.optifine.reflect.Reflector.call(Reflector.java:976) ~[Reflector.class:?]
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1251) ~[Reflector.class:?]
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1237) ~[Reflector.class:?]
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:98) ~[bsb.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:298) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) ~[jh.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) ~[jh.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 9 more
```

**Comment by darklysteamgear** [comment]
Having the same issue. After digging, it seems like there was an attempt to fix this in issue #317. Not too sure what happened.
