### ISSUE TITLE
Crash when entering the Tropics (no other mods)

### ISSUE THREAD

**Issue by HawkDaniels** [Tropicraft/Tropicraft#464]
Just wanted to preface this with a thanks for keeping this mod updated. One of my favorites of all time and glad to see it ported to 1.18

## Issue Description
Crash when entering the Tropical Dimension. No other mods installed.

## Steps to Reproduce
1) Drink Pina Colada at sunset in chair

Tropicraft Version:   v9.3.1 for 1.18.2   
Forge Version:   40.1.0 and 40.1.60   

## Crash log
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 7/11/22, 7:08 PM
Description: Ticking player

net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: portalCooldown
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:227) ~[fmlcore-1.18.2-40.1.0.jar%2354!/:?] {}
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.setPrivateValue(ObfuscationReflectionHelper.java:105) ~[fmlcore-1.18.2-40.1.0.jar%2354!/:?] {}
	at net.tropicraft.core.common.dimension.TropicraftDimension.teleportPlayerWithPortal(TropicraftDimension.java:164) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading,re:mixin}
	at net.tropicraft.core.common.drinks.Drink$1.onDrink(Drink.java:30) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading}
	at net.tropicraft.core.common.drinks.Drink.onDrink(Drink.java:77) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading}
	at net.tropicraft.core.common.item.CocktailItem.onFoodEaten(CocktailItem.java:207) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading}
	at net.tropicraft.core.common.item.CocktailItem.m_5922_(CocktailItem.java:221) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41671_(ItemStack.java:256) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.entity.LivingEntity.m_8095_(LivingEntity.java:2962) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_8095_(ServerPlayer.java:1094) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_142106_(LivingEntity.java:2845) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_142106_(ServerPlayer.java:1567) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_21329_(LivingEntity.java:2830) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2216) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.NoSuchFieldException: portalCooldown
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?] {}
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:221) ~[fmlcore-1.18.2-40.1.0.jar%2354!/:?] {}
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:227) ~[fmlcore-1.18.2-40.1.0.jar%2354!/:?] {}
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.setPrivateValue(ObfuscationReflectionHelper.java:105) ~[fmlcore-1.18.2-40.1.0.jar%2354!/:?] {}
	at net.tropicraft.core.common.dimension.TropicraftDimension.teleportPlayerWithPortal(TropicraftDimension.java:164) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading,re:mixin}
	at net.tropicraft.core.common.drinks.Drink$1.onDrink(Drink.java:30) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading}
	at net.tropicraft.core.common.drinks.Drink.onDrink(Drink.java:77) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading}
	at net.tropicraft.core.common.item.CocktailItem.onFoodEaten(CocktailItem.java:207) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading}
	at net.tropicraft.core.common.item.CocktailItem.m_5922_(CocktailItem.java:221) ~[Tropicraft-9.3.1-beta+3-gha.jar%2352!/:9.3.1-beta+3-gha] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41671_(ItemStack.java:256) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.entity.LivingEntity.m_8095_(LivingEntity.java:2962) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_8095_(ServerPlayer.java:1094) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_142106_(LivingEntity.java:2845) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_142106_(ServerPlayer.java:1567) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_21329_(LivingEntity.java:2830) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2216) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 209
	Entity Name: HawkDaniels
	Entity's Exact location: -3.00, 135.50, 2.00
	Entity's Block location: World: (-3,135,2), Section: (at 13,7,2 in -1,8,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 910515936 bytes (868 MiB) / 2453667840 bytes (2340 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2216
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 38854.88
	Virtual memory used (MB): 24637.64
	Swap memory total (MB): 6345.57
	Swap memory used (MB): 43.45
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['HawkDaniels'/209, l='ServerLevel[New World]', x=-3.00, y=135.50, z=2.00]]
	Data Packs: vanilla, mod:tropicraft (incompatible), mod:forge (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Tropicraft-9.3.1-beta+3-gha.jar                   |Tropicraft                    |tropicraft                    |9.3.1-beta+3-gha    |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.0-universal.jar                 |Forge                         |forge                         |40.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: f22db8f1-4678-4418-8a6e-3659474b0157
	FML: 40.1
	Forge: net.minecraftforge:40.1.0
```

**Comment by Koobaczech** [comment]
Hey! I get the same issue. I can relogin after the crash and play, but traveling back through the portal to the overworld and then heading back to the already created portal at sunset triggers the crash again. Thanks!

**Comment by Dragon-Seeker** [comment]
https://github.com/Tropicraft/Tropicraft/blob/eb45641bfdd13a64a301e2cb33370239086622cc/src/main/java/net/tropicraft/core/common/dimension/TropicraftDimension.java#L164

Seems that the Variable for portal cooldown in the Entity class changed names within the mappings if I am to speculate causing the Reflection helper to not find the needed field and crashing out

**Comment by NotActuallyTerry** [comment]
While we don't have the portal code in, is L164 even required? I can't imagine us actually needing a cooldown after drinking a pina colada

**Comment by Corosauce** [comment]
Portal seems there in latest 1.18 branch, and still helps player get out of the portal after chunk gen happens, before they are force teleported back.

I've now moved portalCooldown to an access transformer which should resolve the crash issue and future proof the feature better. Commit: https://github.com/Tropicraft/Tropicraft/commit/b431d77932f33cb2d20b51e48beec6e171af0f3b
