### ISSUE TITLE
[1.20.1] Crash on sapling growth

### ISSUE THREAD

**Issue by hammertater** [Tropicraft/Tropicraft#546]
**Describe the bug**
Errors are thrown when a sapling attempts to grow into a tree. I think it's only for fruit trees (see error below). I only tried on orange, lime, and lemon trees.

**To Reproduce**
1. Place a lemon (etc.) sapling
2. Wait for the sapling to try to grow (game crashes) or use bonemeal on it (logs an error)

**Versions**
```
Mod List: 
    forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp|Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
    main                                              |HT's TreeChop                 |treechop                      |0.0NONE             |DONE      |Manifest: NOSIGNATURE
    tropicraft-254794-4617294_mapped_official_1.20.1.j|Tropicraft                    |tropicraft                    |9.6.1               |DONE      |Manifest: NOSIGNATURE
                                                      |Forge                         |forge                         |47.1.39             |DONE      |Manifest: NOSIGNATURE
Crash Report UUID: 87783210-e7d8-46b7-ad10-411ac8f7fb61
FML: 47.1
Forge: net.minecraftforge:47.1.39
```

**Additional context**

**Crash log**

Error when using bone meal:

```
[17:19:42] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@38692e46, suppressing error
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "fruitLeaves" is null
	at net.tropicraft.core.common.block.TropicraftTrees.lambda$createFruit$3(TropicraftTrees.java:96) ~[tropicraft-254794-4617294_mapped_official_1.20.1.jar%23198!/:9.6.1] {re:classloading}
	at net.tropicraft.core.common.block.TropicraftTrees$1.growTree(TropicraftTrees.java:134) ~[tropicraft-254794-4617294_mapped_official_1.20.1.jar%23198!/:9.6.1] {re:classloading}
	at net.minecraft.world.level.block.SaplingBlock.advanceTree(SaplingBlock.java:46) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.SaplingBlock.performBonemeal(SaplingBlock.java:60) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:73) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraft.world.item.BoneMealItem.useOn(BoneMealItem.java:36) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:587) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23190%23197!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:245) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:355) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1057) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:32) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:8) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:22) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:17) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:143) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:22) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:770) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:161) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:116) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:753) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:747) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:126) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:733) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:665) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:251) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

Crash on natural growth:

```
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "fruitLeaves" is null
	at net.tropicraft.core.common.block.TropicraftTrees.lambda$createFruit$3(TropicraftTrees.java:96) ~[tropicraft-254794-4617294_mapped_official_1.20.1.jar%23198!/:9.6.1] {re:classloading}
	at net.tropicraft.core.common.block.TropicraftTrees$1.growTree(TropicraftTrees.java:134) ~[tropicraft-254794-4617294_mapped_official_1.20.1.jar%23198!/:9.6.1] {re:classloading}
	at net.minecraft.world.level.block.SaplingBlock.advanceTree(SaplingBlock.java:46) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.SaplingBlock.randomTick(SaplingBlock.java:37) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:762) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:481) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:362) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:312) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:305) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:893) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:814) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:89) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:661) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:251) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

[crash-2023-08-05_17.20.05-server.txt](https://github.com/Tropicraft/Tropicraft/files/12268241/crash-2023-08-05_17.20.05-server.txt)

**Comment by hammertater** [comment]
Unrelated (sorry) but there's also another error (non-crashing) in my log:

```
[17:27:27] [modloading-worker-0/ERROR] [minecraft/Sheets]: net.minecraft.client.renderer.Sheets loaded too early, modded registry-based materials may not work correctly
java.lang.IllegalStateException: net.minecraft.client.renderer.Sheets loaded too early
	at net.minecraft.client.renderer.Sheets.<clinit>(Sheets.java:226) ~[forge-1.20.1-47.1.39_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.tropicraft.core.client.tileentity.BambooChestRenderer.getChestMaterial(BambooChestRenderer.java:33) ~[tropicraft-254794-4617294_mapped_official_1.20.1.jar%23198!/:9.6.1] {re:classloading,pl:runtimedistcleaner:A}
	at net.tropicraft.core.client.tileentity.BambooChestRenderer.<clinit>(BambooChestRenderer.java:20) ~[tropicraft-254794-4617294_mapped_official_1.20.1.jar%23198!/:9.6.1] {re:classloading,pl:runtimedistcleaner:A}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Class.java:467) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.20.1-47.1.39.jar%23192!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.20.1-47.1.39.jar%23192!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.20.1-47.1.39.jar%23192!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.39.jar%23195!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

And a missing sound warning:
```
[17:27:31] [Render thread/WARN] [minecraft/SoundEngine]: Missing sound for event: tropicraft:bongo.med
```

**Comment by Erabior** [comment]
Im also getting this crash on my server

**Comment by natebc** [comment]
getting the original NPE crash reported in this issue on the FTB DW20 1.20.1 pack verion 1.2.0

Issue reported to modpack here: FTBTeam/FTB-Modpack-Issues/issues/4086

Gist with crash-report and server log: https://gist.github.com/natebc/d733833096e32ac4e670128dfd3a9bc3
