### ISSUE TITLE
[1.19.2] Crash entering dimension

### ISSUE THREAD

**Issue by Reshy** [Tropicraft/Tropicraft#547]
**Describe the bug**
Crashed upon attempting to enter dimension (using console commands)

**To Reproduce**
1. Unknown, references to better weather were made, but the two mods on their own don't cause the crash.

**Expected behavior**
Game shouldn't craft upon entering the dimension.

**Versions**
 - Tropicraft Version [Tropicraft-9.5.1.jar]
 - Forge Version [43.2.20]
 - Minecraft Version [1.19.2]

**Stack trace**
```
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "p_129298_" is null
	at net.minecraft.nbt.StringTag.m_129297_(StringTag.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,re:classloading}
	at net.minecraft.nbt.CompoundTag.m_128359_(CompoundTag.java:199) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.nbt_memory_usage.CompoundTagMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.NbtCompoundMixin,pl:mixin:A}
	at corgitaco.betterweather.data.storage.WeatherEventSavedData.m_7176_(WeatherEventSavedData.java:58) ~[betterweather-1.2.jar%23502!/:1.0.0] {re:mixin,re:classloading}
	at net.minecraft.world.level.saveddata.SavedData.m_77757_(SavedData.java:36) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,re:classloading}
	at corgitaco.betterweather.data.storage.WeatherEventSavedData.m_77757_(WeatherEventSavedData.java:53) ~[betterweather-1.2.jar%23502!/:1.0.0] {re:mixin,re:classloading}
	at net.minecraft.world.level.storage.DimensionDataStorage.m_164865_(DimensionDataStorage.java:161) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at net.minecraft.world.level.storage.DimensionDataStorage.m_78151_(DimensionDataStorage.java:159) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8806_(ServerLevel.java:723) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:betterweather.mixins.json:server.world.MixinServerWorld,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:the_bumblezone.mixins.json:world.ServerWorldMixin,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:APP:midnight.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8643_(ServerLevel.java:702) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:betterweather.mixins.json:server.world.MixinServerWorld,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ServerLevelMixin,pl:mixin:APP:the_bumblezone.mixins.json:world.ServerWorldMixin,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.ServerLevelMixin,pl:mixin:APP:alternate-current.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:fabrication.mixins.json:c_tweaks.alt_absorption_sound.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinServerWorld,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinServerWorld,pl:mixin:APP:midnight.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:496) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_195514_(MinecraftServer.java:521) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:76) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

**Crash log**
https://pastebin.com/G0CS5zTT

**Comment by Cojomax99** [comment]
We can look at this if it is still occurring in the latest Minecraft release
